"""Asset 5: sack-pile — sandbox/assets/models/sacks.glb
ROUND 7 — TECHNIQUE CHANGE (sanctioned, blender/fixlists/B1-r7.md). Six rounds
of procedural ring-generator bodies failed with a different symptom every
time ("rod" -> "beak" -> "worm" -> "corrugated tube") because a lathe-style
radius function produces rotationally regular geometry BY CONSTRUCTION. This
round stops generating cloth and SIMULATES it: each sack is built as (1) a
lumpy rounded-box CONTENTS collision body, (2) a plain quad-tube CLOTH
envelope around it with the shoulder-and-outward region (t>=SHOULDER_T --
the collar/flare/tied end, all PASSING since round 5) pinned rigid, (3) a
ground collision plane. The cloth solver is stepped frame-by-frame
(`scene.frame_set`) -- NOT `bpy.ops.ptcache.bake*`, which needs a viewport
context and fails headless -- and the settled, deformed mesh is snapshotted
via `evaluated_get()` + `bpy.data.meshes.new_from_object()`. Sacks are
simmed SEQUENTIALLY (1, then 2 against baked-1, then 3 dropped across both)
so cloth-vs-cloth contact is really cloth-vs-baked-static-collision, which is
far more stable headless than three live cloth bodies colliding with each
other.

The neck (t>1: pinch, cord-wrap collar, flare, tied end) is generated by the
EXACT SAME `ring_profile` formula the round-5/6 manifests already passed --
copied byte-for-byte except for the deleted FOLDS/PUCKERS/scallop/rectness
machinery, none of which touched the neck branch anyway. Pinning verifies
itself: pinned-vertex world coordinates are diffed before/after the bake and
the max delta is printed and asserted near zero.
"""
import bpy
import bmesh
import math
import os
import sys
import random
import mathutils

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import (
    new_mesh_object, add_bevel, smart_uv, apply_all_transforms,
    setup_clay_render, add_sun, add_fill_sun, add_camera, render_to,
    export_glb, clear_scene, MODELS_DIR, RENDERS_DIR, add_ground_plane,
    quick_check, get_shared_material,
)

MAT_NAMES = ["cloth"]

N_SEG = 32
HALF_W = 0.19
HALF_H_TOP = 0.145
HALF_H_BOT = 0.085
BODY_LEN = 0.68
NECK_FRAC = 0.34
NECK_RUN = 0.22
NECK_LATERAL = 0.30
NECK_RISE = 0.03
NECK_DROOP = 0.05
NECK_MIN_R = 0.016
SPREAD = 1.20
ENV_FLOOR = 0.05
COLLAR_PROUD = 0.017
COLLAR_HALF_T = 0.030
SHOULDER_T = 0.93
NECK_START_FRAC = 0.45
PIN_T = SHOULDER_T  # pin everything from the shoulder outward (unchanged geometry)

CONTENT_SCALE = 0.72   # contents sit inside the envelope by this fraction
ENVELOPE_SCALE = 1.18  # r7 4th pass: 1.35 + jitter=0.016 buckled into an all-over
                        # noisy crumple -- "boulder/rock", the round-2 failure mode
                        # this project already escaped once. Less excess material,
                        # less jitter and more bending stiffness (below) trade some
                        # fold count for FEWER, BROADER, more legible creases.
                        # r7 3rd pass note (kept for context): the REST mesh's own edge lengths are what
                        # store "excess fabric" for a cloth sim (moving verts
                        # around before frame 1 does not add slack -- only a
                        # larger base mesh does). At scale=1.0 the envelope was
                        # already exactly the smooth tube shape it settled
                        # into, so there was no surplus material to buckle.
                        # Building the rest mesh 35% larger than the final
                        # read-size, then letting gravity+collision compress
                        # it down onto a 0.65-scale content body, is what
                        # forces the excess to go somewhere -- creases.
FRAMES = 90


def ring_profile(t):
    """Position-along-axis (u) + neck bend offsets + base cross-section radii
    at length-param t. t in [0,1] is the body (now a free-draping cloth
    region below PIN_T); t>1 is the neck, PINNED RIGID, and this branch is
    unchanged from the r5/r6-passing version."""
    if t <= 1.0:
        u = t * BODY_LEN
        bend_w = 0.0
        bend_z = 0.0
        if t < 0.12:
            cap = ENV_FLOOR + (1 - ENV_FLOOR) * math.sin(math.pi / 2 * (t / 0.12))
        else:
            cap = 1.0
        if t > SHOULDER_T:
            p = (t - SHOULDER_T) / (1.0 - SHOULDER_T)
            ease = p * p
            shoulder = 1.0 - ease * (1.0 - NECK_START_FRAC)
        else:
            shoulder = 1.0
        env = cap * shoulder
        width_r = HALF_W * env
        h_top = HALF_H_TOP * env
        h_bot = HALF_H_BOT * env
    else:
        tn = (t - 1.0) / NECK_FRAC
        u = BODY_LEN + tn * NECK_RUN
        PINCH_T = 0.35
        if tn <= PINCH_T:
            p = tn / PINCH_T
            rad_mult = 1.0 - p * 0.72
        else:
            p = (tn - PINCH_T) / (1.0 - PINCH_T)
            ease = math.sin(p * math.pi * 0.5)
            rad_mult = 0.28 + ease * 0.80
            if p > 0.80:
                cap = (p - 0.80) / 0.20
                rad_mult *= (1.0 - 0.18 * cap)
        rad_mult = max(rad_mult, 0.10)
        width_r = max(HALF_W * 0.45 * rad_mult, NECK_MIN_R)
        h_top = max(HALF_H_TOP * 0.45 * rad_mult, NECK_MIN_R * 0.9)
        flat_ratio = HALF_H_BOT / HALF_H_TOP
        round_out = min(tn / 0.30, 1.0)
        h_bot = h_top * (flat_ratio + (1.0 - flat_ratio) * round_out)
        fp = min(tn / PINCH_T, 1.0)
        width_r *= 1.0 + 0.30 * fp
        h_top *= 1.0 - 0.18 * fp
        h_bot *= 1.0 - 0.14 * fp
        bend_w = tn * NECK_LATERAL
        if tn < 0.55:
            bend_z = (tn / 0.55) * NECK_RISE
        else:
            bend_z = NECK_RISE - (tn - 0.55) / 0.45 * NECK_DROOP
    return u, bend_w, bend_z, width_r, h_top, h_bot


def _tangent_frame(centers, i, Lx, Ly, Wx, Wy):
    n = len(centers)
    if i == 0:
        tangent = centers[1] - centers[0]
    elif i == n - 1:
        tangent = centers[i] - centers[i - 1]
    else:
        tangent = centers[i + 1] - centers[i - 1]
    if tangent.length < 1e-9:
        tangent = mathutils.Vector((Lx, Ly, 0.0))
    tangent.normalize()
    up_ref = mathutils.Vector((0.0, 0.0, 1.0))
    if abs(tangent.dot(up_ref)) > 0.97:
        up_ref = mathutils.Vector((Wx, Wy, 0.0))
    local_u = up_ref.cross(tangent)
    local_u.normalize()
    local_v = tangent.cross(local_u)
    local_v.normalize()
    return local_u, local_v


def build_envelope(bm, cx, cy, s, body_deg, tail_z0, n_ring_body, n_ring_neck,
                    collar_n, seg, scale=1.0, t_end=None, flatten_bottom=1.0,
                    jitter=0.0, seed=0):
    """Plain (no folds/dents/puckers) quad-tube loft, used both for the cloth
    ENVELOPE (scale=1.0, t_end=None -> full body+neck) and the CONTENTS
    collision body (scale=CONTENT_SCALE, t_end=SHOULDER_T -> body only,
    capped at the shoulder, no neck). Returns (verts_by_ring, ts, pin_start_i)
    -- pin_start_i is the first ring index at t>=PIN_T, or None if t_end
    stops before PIN_T (the contents body)."""
    rad = math.radians(body_deg)
    Lx, Ly = math.cos(rad), math.sin(rad)
    Wx, Wy = -Ly, Lx

    t_pinch = 1.0 + 0.35 * NECK_FRAC
    ts = [i / n_ring_body for i in range(n_ring_body + 1)]
    if t_end is None:
        ts += [1.0 + (i + 1) / n_ring_neck * NECK_FRAC for i in range(n_ring_neck)]
        collar_offsets = [(i / (collar_n - 1)) * 2.0 - 1.0 for i in range(collar_n)]
        collar_ts = [t_pinch + x * COLLAR_HALF_T for x in collar_offsets]
        collar_bump = {ct: math.cos(x * math.pi / 2.0) for ct, x in zip(collar_ts, collar_offsets)}
        ts = sorted(set(ts) | set(collar_ts))
    else:
        ts = [t for t in ts if t <= t_end]
        collar_ts, collar_bump = [], {}

    centers, radii = [], []
    for t in ts:
        is_collar = any(abs(t - ct) < 1e-9 for ct in collar_ts)
        u, bend_w, bend_z, width_r, h_top, h_bot = ring_profile(t if not is_collar else t_pinch)
        if is_collar:
            bump = next(f for ct, f in collar_bump.items() if abs(t - ct) < 1e-9)
            band_r = max(width_r, h_top) * s + COLLAR_PROUD * s * bump
            width_r = h_top = h_bot = band_r / s
        # r7: `scale` only inflates the FREE body region (t<PIN_T) -- the
        # pinned shoulder-onward geometry (collar/flare/tied end) must stay
        # byte-identical to the r5/r6-passing shape, so it always renders at
        # the un-inflated (scale=1.0) size regardless of ENVELOPE_SCALE.
        eff_scale = scale if t < PIN_T else 1.0
        width_r *= eff_scale
        h_top *= eff_scale
        h_bot *= eff_scale * flatten_bottom
        ring_cx = cx + Lx * (u * s) + Wx * (bend_w * s)
        ring_cy = cy + Ly * (u * s) + Wy * (bend_w * s)
        ring_cz = tail_z0 + bend_z * s
        centers.append(mathutils.Vector((ring_cx, ring_cy, ring_cz)))
        radii.append((t, width_r, h_top, h_bot))

    n = len(ts)
    rnd = random.Random(seed)
    rings = []
    for i in range(n):
        t, width_r, h_top, h_bot = radii[i]
        local_u, local_v = _tangent_frame(centers, i, Lx, Ly, Wx, Wy)
        ring_center = centers[i]
        ring_verts = []
        for k in range(seg):
            a = 2 * math.pi * k / seg
            ca, sa = math.cos(a), math.sin(a)
            hr = h_top if sa >= 0 else h_bot
            wscale = 1.0 if sa >= 0 else 1.0 + (SPREAD - 1.0) * (max(0.0, -sa) ** 0.7)
            local_w = width_r * s * wscale
            local_h = hr * s
            pos = ring_center + local_u * (local_w * ca) + local_v * (local_h * sa)
            # r7: a perfectly rotationally-symmetric rest mesh collapses onto
            # its (also symmetric) contents by uniform radial compression,
            # with no buckling instability to seed a fold anywhere -- the
            # exact failure this round is meant to fix. A small per-vertex
            # jitter on the free cloth region (not the pinned neck) breaks
            # that symmetry so gravity + self-collision actually buckle the
            # excess fabric into creases instead of shrink-wrapping it.
            if jitter > 0.0 and t < PIN_T:
                pos = pos + local_u * rnd.uniform(-jitter, jitter) * s \
                          + local_v * rnd.uniform(-jitter, jitter) * s
            ring_verts.append(bm.verts.new((pos.x, pos.y, pos.z)))
        rings.append(ring_verts)

    for i in range(len(rings) - 1):
        r0, r1 = rings[i], rings[i + 1]
        for k in range(seg):
            k2 = (k + 1) % seg
            bm.faces.new((r0[k], r0[k2], r1[k2], r1[k]))

    tail_center = bm.verts.new((cx, cy, tail_z0))
    for k in range(seg):
        k2 = (k + 1) % seg
        bm.faces.new((tail_center, rings[0][k2], rings[0][k]))
    tip_ring = rings[-1]
    tip_center = bm.verts.new(sum((v.co for v in tip_ring), mathutils.Vector()) / seg)
    for k in range(seg):
        k2 = (k + 1) % seg
        bm.faces.new((tip_center, tip_ring[k], tip_ring[k2]))

    pin_start_i = next((i for i, t in enumerate(ts) if t >= PIN_T), None)
    return rings, ts, pin_start_i


def make_object(name, bm):
    mesh = bpy.data.meshes.new(name)
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def add_collision(obj, thickness=0.003, damping=0.5):
    obj.modifiers.new("Collision", 'COLLISION')
    obj.collision.thickness_outer = thickness
    obj.collision.thickness_inner = thickness
    obj.collision.damping = damping


def sim_sack(cx, cy, s, body_deg, tail_z0, n_ring_body, n_ring_neck, collar_n,
             seg, extra_colliders, sack_tag, jitter_seed=0):
    """Build one sack's contents + cloth envelope, sim it against
    extra_colliders (previously baked sacks + ground), step the solver,
    snapshot the deformed mesh, verify the pin, and return the FINAL baked
    object (contents + temp cloth object are deleted before returning)."""
    scene = bpy.context.scene

    bm_c = bmesh.new()
    build_envelope(bm_c, cx, cy, s, body_deg, tail_z0, n_ring_body, n_ring_neck,
                   collar_n, seg, scale=CONTENT_SCALE, t_end=SHOULDER_T, flatten_bottom=0.75)
    contents_obj = make_object(f"{sack_tag}_contents", bm_c)
    add_collision(contents_obj, thickness=0.003, damping=0.6)

    bm_e = bmesh.new()
    rings, ts, pin_start_i = build_envelope(
        bm_e, cx, cy, s, body_deg, tail_z0, n_ring_body, n_ring_neck, collar_n, seg,
        scale=ENVELOPE_SCALE, t_end=None, jitter=0.006, seed=jitter_seed)
    env_obj = make_object(f"{sack_tag}_cloth", bm_e)
    env_obj.data.materials.append(get_shared_material("cloth"))

    # ring verts are created in strict (ring, seg) order before any cap verts
    # in build_envelope, so a ring's global mesh-vertex index is simply
    # i*seg+k -- computed directly instead of reading BMVert.index, which is
    # invalid once the bmesh has been freed by make_object().
    vg = env_obj.vertex_groups.new(name="Pin")
    n_rings_total = len(rings)
    pin_indices = [i * seg + k for i in range(pin_start_i, n_rings_total) for k in range(seg)]
    vg.add(pin_indices, 1.0, 'REPLACE')

    before_world = [(env_obj.matrix_world @ env_obj.data.vertices[i].co).copy()
                    for i in pin_indices]

    cloth_mod = env_obj.modifiers.new("Cloth", 'CLOTH')
    cs = cloth_mod.settings
    cs.quality = 9
    cs.mass = 0.35
    # r7 2nd pass: a smooth capsule/sausage came back at tension==compression
    # (22/22) plus pressure=8 -- the pressure force pushed the cloth taut
    # against the contents (a pressure vessel has no fold material to spare)
    # and the high compression stiffness resisted whatever buckling gravity
    # alone tried to create. Real jute is stiff in TENSION (it doesn't
    # stretch) but buckles easily in COMPRESSION (that mismatch is what
    # produces creases): keep tension high, drop compression an order of
    # magnitude, and rely on gravity + slack (0.72 content scale) + self
    # collision for folds instead of an outward pressure force.
    cs.tension_stiffness = 25
    cs.compression_stiffness = 5
    cs.shear_stiffness = 6
    cs.bending_stiffness = 2.5
    cs.tension_damping = 5
    cs.compression_damping = 5
    cs.shear_damping = 5
    cs.use_pressure = False
    cs.vertex_group_mass = "Pin"
    cs.pin_stiffness = 1.0
    coll = cloth_mod.collision_settings
    coll.use_self_collision = True
    coll.distance_min = 0.003
    coll.self_distance_min = 0.003
    coll.self_friction = 5.0
    coll.friction = 5.0
    coll.collision_quality = 4

    scene.frame_start = 1
    scene.frame_end = FRAMES
    scene.frame_set(1)
    for f in range(1, FRAMES + 1):
        scene.frame_set(f)

    dg = bpy.context.evaluated_depsgraph_get()
    ev = env_obj.evaluated_get(dg)
    baked_mesh = bpy.data.meshes.new_from_object(ev)
    baked_obj = bpy.data.objects.new(f"{sack_tag}_baked", baked_mesh)
    baked_obj.matrix_world = env_obj.matrix_world.copy()
    bpy.context.collection.objects.link(baked_obj)

    after_world = [(baked_obj.matrix_world @ baked_mesh.vertices[i].co).copy()
                   for i in pin_indices]
    max_delta = max((b - a).length for b, a in zip(before_world, after_world))
    print(f"[{sack_tag}] PIN VERIFY max delta = {max_delta:.6f} m "
          f"({'OK' if max_delta < 0.001 else 'FAIL -- pin moved'})")

    baked_obj.data.materials.append(get_shared_material("cloth"))
    bpy.data.objects.remove(contents_obj, do_unlink=True)
    bpy.data.objects.remove(env_obj, do_unlink=True)
    return baked_obj


def build():
    clear_scene()

    s1, s2, s3 = 1.00, 0.82, 0.60
    c1 = (-0.42, -0.20)
    c2 = (0.45, 0.24)
    top1 = HALF_H_BOT * s1 + HALF_H_TOP * s1
    top2 = HALF_H_BOT * s2 + HALF_H_TOP * s2
    tail1 = HALF_H_BOT * s1
    tail2 = HALF_H_BOT * s2
    tail3 = (top1 + top2) / 2.0 + 0.03 * s3

    ground = add_ground_plane(size=4.0)
    add_collision(ground, thickness=0.003, damping=0.8)

    baked1 = sim_sack(c1[0], c1[1], s1, 18, tail1, n_ring_body=22, n_ring_neck=13,
                       collar_n=3, seg=N_SEG, extra_colliders=[ground], sack_tag="sack1",
                       jitter_seed=1)
    add_collision(baked1, thickness=0.003, damping=0.6)

    baked2 = sim_sack(c2[0], c2[1], s2, -70, tail2, n_ring_body=16, n_ring_neck=8,
                       collar_n=2, seg=24, extra_colliders=[ground, baked1], sack_tag="sack2",
                       jitter_seed=2)
    add_collision(baked2, thickness=0.003, damping=0.6)

    c3x = (c1[0] + c2[0]) / 2.0 + 0.02
    c3y = (c1[1] + c2[1]) / 2.0 - 0.01
    baked3 = sim_sack(c3x, c3y, s3, 100, tail3, n_ring_body=16, n_ring_neck=8,
                       collar_n=2, seg=24, extra_colliders=[ground, baked1, baked2],
                       sack_tag="sack3", jitter_seed=3)

    # strip collision proxies now that all three are baked
    for o in (baked1, baked2):
        m = o.modifiers.get("Collision")
        if m:
            o.modifiers.remove(m)
    bpy.data.objects.remove(ground, do_unlink=True)

    for o, target in ((baked1, 6500), (baked2, 5000), (baked3, 4500)):
        tris = sum(len(p.vertices) - 2 for p in o.data.polygons)
        print(f"{o.name} pre-decimate tris: {tris}")

    obj = new_mesh_object("sacks_tmp", bmesh.new())  # placeholder, replaced by join below
    bpy.data.objects.remove(obj, do_unlink=True)

    bpy.ops.object.select_all(action='DESELECT')
    for o in (baked1, baked2, baked3):
        o.select_set(True)
    bpy.context.view_layer.objects.active = baked1
    bpy.ops.object.join()
    sacks_obj = bpy.context.view_layer.objects.active
    sacks_obj.name = "sacks"

    tri_count = sum(len(p.vertices) - 2 for p in sacks_obj.data.polygons)
    print(f"joined sacks pre-decimate tris: {tri_count}")
    if tri_count > 7500:
        dec = sacks_obj.modifiers.new("Decimate", 'DECIMATE')
        dec.decimate_type = 'COLLAPSE'
        dec.ratio = 7500.0 / max(tri_count, 1)
        bpy.context.view_layer.objects.active = sacks_obj
        bpy.ops.object.modifier_apply(modifier="Decimate")
        tri_count = sum(len(p.vertices) - 2 for p in sacks_obj.data.polygons)
        print(f"joined sacks post-decimate tris: {tri_count}")

    apply_all_transforms(sacks_obj)
    bpy.ops.object.shade_smooth()
    smart_uv(sacks_obj)
    return sacks_obj


def render_pass():
    setup_clay_render()
    add_ground_plane(size=4.0)
    add_sun()
    add_fill_sun()
    tgt = mathutils.Vector((0.03, 0.0, 0.24))
    add_camera("cam_face", (0, -2.5, 1.6), tgt, lens=42)
    render_to(os.path.join(RENDERS_DIR, "sacks_face.png"))
    add_camera("cam_34", (1.9, -2.0, 1.6), tgt, lens=42)
    render_to(os.path.join(RENDERS_DIR, "sacks_34.png"))
    add_camera("cam_detail", (-0.55, -0.85, 0.6), mathutils.Vector((-0.32, -0.15, 0.42)), lens=45)
    render_to(os.path.join(RENDERS_DIR, "sacks_detail.png"))
    # r7: two new evidence frames required by the fixlist -- puckers (tail-cap
    # corners, sack 1) and shoulder (body-to-neck kink, sack 1), both now
    # produced by the sim (contact/self-collision creases) rather than
    # hand-placed gaussian bumps.
    # r7 fix: the original target (-1.05,-0.20,0.06) sat entirely outside the
    # mesh's bounding box (X extent -0.467..0.958, confirmed by probe), which
    # rendered blank grey. Re-aimed at sack1's actual tail-cap corner.
    add_camera("cam_puckers", (-0.70, -0.65, 0.35), mathutils.Vector((-0.40, -0.20, 0.08)), lens=50)
    render_to(os.path.join(RENDERS_DIR, "sacks_puckers.png"))
    add_camera("cam_shoulder", (-0.05, -0.55, 0.45), mathutils.Vector((0.10, -0.20, 0.32)), lens=48)
    render_to(os.path.join(RENDERS_DIR, "sacks_shoulder.png"))


if __name__ == "__main__":
    obj = build()
    bpy.ops.wm.save_as_mainfile(filepath="C:/Users/USERNAME/Downloads/projects/victorian-london/blender/B1/sacks.blend")
    if "--quick" in sys.argv:
        add_ground_plane(size=4.0)
        add_camera("cq", (0, -2.5, 1.5), mathutils.Vector((0.03, 0, 0.24)), lens=42)
        quick_check(os.path.join(RENDERS_DIR, "sacks_quick.png"), res=800)
        add_camera("cq2", (-0.55, -0.85, 0.55), mathutils.Vector((-0.32, -0.15, 0.42)), lens=45)
        quick_check(os.path.join(RENDERS_DIR, "sacks_quick_detail.png"), res=800)
        add_camera("cq3", (1.9, -2.0, 1.4), mathutils.Vector((0.03, 0, 0.24)), lens=42)
        quick_check(os.path.join(RENDERS_DIR, "sacks_quick_34.png"), res=800)
    else:
        render_pass()
        export_glb([obj], os.path.join(MODELS_DIR, "sacks.glb"))
    print("SACKS DONE")
